# Generated by Django 3.0.4 on 2020-03-08 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_depenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense',
            name='suivi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='suivi_depenses.Suivi'),
        ),
    ]
