# Generated by Django 3.0.4 on 2020-03-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suivi_depenses', '0002_auto_20200308_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorie',
            name='suivi',
        ),
    ]
