# Generated by Django 3.0.4 on 2020-03-11 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suivi_depenses', '0003_remove_categorie_suivi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
        migrations.AlterModelOptions(
            name='depense',
            options={'ordering': ('-montant',)},
        ),
        migrations.AddField(
            model_name='suivi',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to=settings.AUTH_USER_MODEL),
        ),
    ]
